<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-3TRPJN2F" failures="0" tests="1" name="Functional Test" time="18.374" errors="0" timestamp="2023-12-14T19:55:16 IST">
  <testcase classname="com.infy.testcases.LoginLogoutFunctionality" name="verifyLoginLogoutFunctionality" time="5.563"/>
  <testcase classname="com.infy.testcases.LoginLogoutFunctionality" name="TestCase1" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.infy.testcases.LoginLogoutFunctionality" name="TestCase2" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase2 -->
  <testcase classname="com.infy.testcases.LoginLogoutFunctionality" name="verifyErrorMessageWhileLoginWithInvalidCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyErrorMessageWhileLoginWithInvalidCredentials -->
  <testcase classname="com.infy.testcases.LoginLogoutFunctionality" name="verifyLoginIsSuccessfulWithGivenCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginIsSuccessfulWithGivenCredentials -->
</testsuite> <!-- Functional Test -->
